IRCC-ca/ds-sdc-dev

core-library/package-lock.json
core-library/package.json
core-library/tokens/button/_plain.scss

Migrated [PR](https://github.com/IRCC-ca/ds-sdc/pull/410)

Plain button: change background to transparent

---

component-library/component-lib/src/lib/checkbox/checkbox.component.html
component-library/component-lib/src/lib/checkbox/checkbox.component.ts
component-library/component-lib/src/lib/error/error.component.html
component-library/component-lib/src/shared/interfaces/component-configs.ts
component-library/src/app/gallery/QA/michael/michael.component.ts
core-library/component-styling/checkbox/_checkbox.scss

Checkbox: integrate lib-error

---

component-library/component-lib/src/lib/radio-input/radio-input.component.html
component-library/component-lib/src/lib/radio-input/radio-input.component.ts
component-library/src/app/gallery/QA/auto-tester/auto-tester.component.html
component-library/src/app/gallery/QA/auto-tester/auto-tester.component.scss
component-library/src/app/gallery/QA/mahsa/mahsa.component.html
component-library/src/app/gallery/QA/mahsa/mahsa.component.ts
component-library/src/app/gallery/QA/mike/mike.component.html
component-library/src/app/gallery/QA/mike/mike.component.ts

- Updated error msg on Select dropdown component to work conditionally based on options
- Added error msg for Input radio component

Radio Input & Select Dropdown/lib error

---

component-library/component-lib/src/lib/dropdown-input/dropdown-input.component.html
component-library/component-lib/src/lib/input/input.component.html
component-library/component-lib/src/lib/radio-input/radio-input.component.html

- Removed "required" from Select dropdown, Radio Input and Input components

Removed required text

---

component-library/component-lib/src/lib/input/input.component.ts
component-library/component-lib/src/lib/radio-input/radio-input.component.html
component-library/component-lib/src/lib/radio-input/radio-input.component.ts
component-library/src/app/gallery/QA/mike/mike.component.html
component-library/src/app/gallery/QA/mike/mike.component.ts
core-library/component-styling/autocomplete/_autocomplete.scss
core-library/component-styling/error/_error.scss
core-library/component-styling/radio/_radio.scss
core-library/tokens/input/_input.scss
core-library/tokens/radio/_radio.scss

- updating radio component + styling
- fixing bug with error component styles
- fixing input bug

radio component refactor and qa

---

component-library/component-lib/src/lib/input/input.component.ts
component-library/component-lib/src/lib/language-switch/language-switch.component.ts
component-library/src/app/gallery/QA/naseer/naseer.component.html
component-library/src/app/gallery/QA/naseer/naseer.component.ts
core-library/component-styling/button/_button.scss
core-library/component-styling/icon/_icon.scss

- Bug fixes on input QA page
- Changed button styles to match design
- Added disable button for button QA
- Changed language toggle breakpoints after checking with design

Bug fixes naseer

---

component-library/component-lib/src/lib/radio-input/radio-input.component.html

- Added Aria-label to label of options (radio input component)

Added aria-label

---

core-library/component-styling/banner/_banner.scss

Meaningful fix are in https://github.com/IRCC-ca/ds-sdc-dev/pull/72/commits/6bfc8e9fe526f073df47b1b5d1b9096017942118 , with others as automatic stylelint fix.

Banner: padding fix

---

component-library/component-lib/src/lib/checkbox/checkbox.component.html
core-library/component-styling/checkbox/_checkbox.scss

- Label color, font family
- Click label should not check checkbox

Checkbox Component- Checkbox title is not using the correct color style.

---

core-library/component-styling/tabs/_tabs.scss

- Updated style to make Tabs scrollable for all devices

Making tab scrollable for all devices

---

component-library/component-lib/src/lib/header-footer/footer/footer.component.html
component-library/component-lib/src/lib/header-footer/footer/footer.component.ts
component-library/src/app/accessibility-demo/accessibility-demo.component.html
component-library/src/translations/en-US.json
core-library/component-styling/footer/_footer.scss

- Add footer component and attached to the page
- Update css for footer component

Add footer to project acc mvp

---

component-library/component-lib/src/lib/shared/progress-indicator/progress-indicator.component.ts
component-library/src/app/gallery/test-page/test-page.component.ts

Removed formGroup

---

component-library/component-lib/src/lib/header-footer/footer/footer.component.html
component-library/component-lib/src/lib/header-footer/header/header.component.html
component-library/component-lib/src/lib/header-footer/header/header.component.ts
component-library/src/translations/en-US.json
component-library/src/translations/fr-FR.json

- Fix bug for footer. Removed the source image that is cause issue. Since we dont support dark mode is has been removed
- Wrap header image with a tag to link to the official Gov of Canada website and accessibility tags

Add Header link and alt text

---

component-library/component-lib/src/lib/form-components/date-picker/date-picker.component.ts
component-library/src/app/accessibility-demo/accessibility-demo.component.ts
component-library/src/translations/en-US.json

error text change and day drop down fix

error text change and day drop down fix

---

core-library/component-styling/header/_header.scss

- Fixed the Header based on the width of page

Fixed header size based on the full with

---

core-library/component-styling/progress-indicator/_progress-indicator.scss

- Added padding to fix the issue with Focus state

Added padding to remove the focus issue

---

component-library/component-lib/src/lib/form-components/date-picker/date-picker.component.ts
component-library/src/app/accessibility-demo/accessibility-demo.component.ts

- Added max-year and min-year logic to the date-picker
- Added number to month options as value
- Added unknown toggle for day month and year
- Enabled unknown toggle for date of birth on accessibility page

Date picker additional tasks

---

component-library/src/app/accessibility-demo/accessibility-demo.component.html
component-library/src/app/accessibility-demo/accessibility-demo.component.scss
core-library/component-styling/button/_button.scss
core-library/component-styling/footer/_footer.scss

- Adjusted Footer for Mobile and Tablet view
- Updated button size based on the screen size

Bug/footer & button on mobile view

---

core-library/_index.scss
core-library/component-styling/footer/_footer.scss
core-library/component-styling/header/_header.scss
core-library/component-styling/language-switch/_language-switch.scss

- **Footer on Tablet mode:**
- **Canada img margin:**
- **Header - French btn on Tablet mode:**
- **Header - Canada flag on Tablet mode:**
- **French toggle font-size**

Updated the headr and footer styles

---

component-library/src/app/@shared/directives/prevent-tab-out.directive.ts
component-library/src/app/accessibility-demo/accessibility-demo-previous-page/accessibility-demo-previous-page.component.html
component-library/src/app/accessibility-demo/accessibility-demo-previous-page/accessibility-demo-previous-page.component.ts
component-library/src/app/accessibility-demo/accessibility-demo.component.html
component-library/src/app/accessibility-demo/accessibility-demo.component.ts

made tab trap for modal

---

core-library/component-styling/select/_select-component.scss

Bug [ticket](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_boards/board/t/JL%20-%20Design%20System/Backlog%20items/?workitem=888006)

Updated select dropdown padding

---

component-library/component-lib/src/lib/shared/indicator/indicator.component.html
component-library/component-lib/src/lib/shared/indicator/indicator.component.ts
component-library/component-lib/src/lib/shared/ircc-ds-angular-component-shared.module.ts
component-library/component-lib/src/public-api.ts
component-library/src/app/gallery/QA/michael/michael.component.html
component-library/src/app/gallery/QA/michael/michael.component.ts
core-library/_index.scss
core-library/component-styling/indicator/_indicator.scss
core-library/tokens/indicator/_indicator.scss

Indicator Component

---

component-library/component-lib/src/lib/form-components/checkbox/checkbox.component.html
component-library/component-lib/src/lib/form-components/checkbox/checkbox.component.ts
component-library/src/app/gallery/QA/michael/michael.component.ts

Checkbox: fix help text

---

component-library/component-lib/src/lib/shared/spinner/spinner.component.html
component-library/component-lib/src/lib/shared/spinner/spinner.component.ts
component-library/src/app/gallery/QA/mahsa/mahsa.component.html
component-library/src/app/gallery/QA/mahsa/mahsa.component.scss
component-library/src/app/gallery/QA/mahsa/mahsa.component.ts

- There is two btns that show and hide the Spinner
- Spinner will update after to second to Success or Error (for testing voice accessibility)

Accessibility for Spinner icons

---

core-library/component-styling/select/_select-component.scss

- Fixed background color and border-width for the select component for firefox.

set background color and border-width to fix some minor bugs on Firefox

---

component-library/component-lib/src/lib/shared/spinner/spinner.component.html
core-library/component-styling/spinner/_spinner.scss

- Updated label and description to pass them through innerHTML
- Updated style for different sizes and orientations

Updated label and desc with innerHTML + update style

---

component-library/component-lib/src/lib/form-components/select/select.component.html
component-library/component-lib/src/lib/form-components/select/select.component.ts
core-library/component-styling/select/_select-component.scss

Added chevron behavior when select is clicked.

Select chevron behavior

---

component-library/src/app/gallery/QA/naseer/naseer.component.ts
component-library/src/app/gallery/QA/qa-routing.module.ts
component-library/src/app/gallery/QA/qa.component.ts
component-library/src/app/gallery/nav-buttons/nav-buttons.component.html
component-library/src/translations/en-US.json
component-library/src/translations/fr-FR.json

Routing bug (cleanup)

---

component-library/component-lib/src/lib/form-components/select/select.component.html
component-library/src/app/gallery/QA/mahsa/mahsa.component.html
component-library/src/app/gallery/QA/mahsa/mahsa.component.ts

- Put back error mgs and Btns on QA page
- Adjusted Size for Select error msg

Fixed QA for Select + Error Size

---

.husky/pre-commit
component-library/angular.json
component-library/component-lib/tsconfig.json
component-library/src/app/@shared/directives/prevent-tab-out.directive.ts
component-library/src/app/accessibility-demo/accessibility-demo-next-page/accessibility-demo-next-page.component.ts
component-library/src/app/accessibility-demo/accessibility-demo-previous-page/accessibility-demo-previous-page.component.html
component-library/src/app/accessibility-demo/accessibility-demo-previous-page/accessibility-demo-previous-page.component.ts
component-library/src/app/accessibility-demo/accessibility-demo.component.html
component-library/src/app/accessibility-demo/accessibility-demo.component.ts
component-library/src/app/gallery/QA/mahsa/mahsa.component.ts
component-library/src/app/gallery/QA/michael/michael.component.ts
component-library/src/app/gallery/QA/mike/mike.component.ts
component-library/src/app/gallery/QA/naseer/naseer.component.ts
component-library/src/app/gallery/landing-page/landing-page.component.ts
component-library/src/app/gallery/nav-buttons/nav-buttons.component.ts
component-library/src/app/home/home.component.ts
component-library/src/app/shell/shell.component.ts
component-library/src/typings.d.ts
package-lock.json
package.json

Adding Husky to enable linting on the pre-commit hook. The linter uses the default Angular linting options.

Add linting on pre-commit

---

component-library/component-lib/src/lib/form-components/error/error.component.html
core-library/component-styling/error/_error.scss

- Adjusted the margin for error message in Large/Small states

Fixed the size and margin for err msg

---

component-library/src/app/gallery/QA/mahsa/mahsa.component.ts

- No more text would leave after deleting the Description, Label and Hint

Fixed the texts after deleting

---

component-library/src/app/gallery/QA/mahsa/mahsa.component.ts
component-library/src/app/gallery/landing-page/landing-page.component.html
component-library/src/app/gallery/nav-buttons/nav-buttons.component.ts
core-library/component-styling/breadcrumb/_breadcrumb.scss
core-library/component-styling/chips/_secondary.scss
core-library/component-styling/indicator/_indicator.scss
core-library/component-styling/label/_label-component.scss
core-library/component-styling/language-switch/_language-switch.scss
core-library/component-styling/progress-indicator/_progress-indicator.scss
core-library/component-styling/progress-tags/_progress-tags.scss
core-library/component-styling/select/_select-component.scss
core-library/component-styling/spinner/_spinner.scss
core-library/tokens/checkbox/_checkbox.scss
core-library/typography/_typography.scss

- Added font-weight to fontSet mix-in
- Updated every where we used fontSet to include font-weight

Update/font set to include font-weight

---

component-library/src/app/components/resizable-container/resizable-container.component.html
component-library/src/app/components/resizable-container/resizable-container.component.scss
component-library/src/app/components/resizable-container/resizable-container.component.ts

Resizable component that will be used in the code viewer component

Resizable component

---

component-library/src/app/components/interactive-demo/interactive-demo.component.scss
component-library/src/app/components/title-slug-url/title-slug-url.component.scss
component-library/src/app/pages/banner-documentation/banner-documentation.component.ts

- Added missing divider on interactive demo
- Changed slug title type to secondary
- Fixed margin issue on slug title

Bug fix interactive demo

---

component-library/src/app/pages/input-documentation/input-documentation.component.html
component-library/src/app/pages/input-documentation/input-documentation.component.scss

Remove innerHTML for 2 list items I missed and small design fix to center the page with margins

Qa/input doc static - small fix

---

component-library/component-lib/src/lib/shared/breadcrumb/breadcrumb.component.html
component-library/src/app/pages/QA/michael/michael.component.html
component-library/src/app/pages/QA/michael/michael.component.scss
component-library/src/app/pages/QA/michael/michael.component.ts
core-library/component-styling/breadcrumb/_breadcrumb.scss

Breadcrumb: centre overflow menu to elipsis

---

component-library/component-lib/src/lib/form-components/checkbox/checkbox.component.html
component-library/component-lib/src/lib/form-components/date-picker/date-picker.component.html
component-library/component-lib/src/lib/form-components/input/input.component.html
component-library/component-lib/src/lib/form-components/radio-input/radio-input.component.html
component-library/component-lib/src/lib/form-components/select/select.component.html
component-library/src/app/pages/QA/accessibility-demo/accessibility-demo.component.html
component-library/src/app/pages/QA/accessibility-demo/accessibility-demo.component.ts
component-library/src/app/shell/shell.component.html
core-library/component-styling/date-picker/_date-picker.scss

**Why are these changes introduced?** 
- Related story #[903497](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/903497)
- Date of birth dropdowns for Year, Month and Day should be in all in fieldset.
- Invalid ARIA attribute value: aria-invalid="[object Object]" (10 different occurrences)
- Duplicate ID (2 different occurrences) 
- Move body section to `<main>` tag
- on submit click if there are errors move focus to missing information div
- hitting enter when within the input should not trigger the info dialogue
- Pulled the PR locally, run npm install and test the changes
- Check for responsiveness
URL: http://localhost:4200/en/accessibility-demo

Accessibility demo fix - Michael

---

component-library/src/app/shell/shell.component.html
component-library/src/app/shell/shell.component.scss

**Why are these changes introduced?** 
- Related [story](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_boards/board/t/JL%20-%20Design%20System/Backlog%20items/?workitem=874921)
- Correct heading title to h4 on mobile

Heading style: h4 on mobile

---

core-library/component-styling/error/_error.scss

* Related story #(https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/907992)
* Small bug fix to set the top margin of inline error text to 4px and better align with the icon
':void' is removed from void functions
* Ensure the code contain appropriate media queries and accessibility elements
* Is the acceptance criteria met?
**Review component …

Bug Story: 907992 All large error messages

---

component-library/src/app/pages/banner-documentation/banner-doc-code.component.ts

* Had a discussion with Tony, who suggested these changes after QA'ing my banner-doc story
* Fixed layout of interactive component for banner to match figma
* Added default value for size in banner config
':void' is removed from void functions
* Ensure the code contain appropriate media queries and accessibility elements
* Is the acceptance criteria met?
**Review component stylesheets:** …

Bug-Fix/banner code block and interactive component

---

component-library/component-lib/src/lib/form-components/input/input.component.html
component-library/component-lib/src/lib/form-components/select/select.component.html
core-library/component-styling/input-component/_input-component.scss
core-library/component-styling/select/_select-component.scss
core-library/component-styling/tabs/_tabs.scss
core-library/tokens/partial/_focus.scss

-resolving various bugs raised in ADO.
-fixing focus for inputs, selects and tabs
-fixing select options when an error message pops up on a windows device (bug was windows specific)
-fixing password show/hide icon by increase z-index

bugfixes for focus and select options

---

component-library/component-lib/src/lib/shared/navigation/nav-item-heading/nav-item-heading.component.html
core-library/component-styling/navigation/navigation-header.scss
core-library/component-styling/navigation/navigation.scss

Very minor updates for header-nav-item

header updates

---

.gitignore
component-library/component-lib/src/lib/shared/breadcrumb/breadcrumb.component.ts

- Fix [907950](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/907950)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-breadcrumb_ellipsis/en/michael-en)
- change ellipsis icon to light font weight
- Compare ellipsis icon with figma

Breadcrumb - Fix ellipsis icon

---

core-library/tokens/global/_validation.scss

Quick two line fix for a critical-text bug.

critical text fix

---

component-library/component-lib/src/lib/shared/icon-button/icon-button.component.html
core-library/component-styling/icon-button/_icon-button.scss

icon-btn-fix

---

component-library/component-lib/src/lib/header-footer/footer/footer.component.html
component-library/component-lib/src/lib/header-footer/footer/footer.component.ts
component-library/component-lib/src/lib/header-footer/header/header.component.html
component-library/component-lib/src/lib/header-footer/header/header.component.ts

- Removed aria-label from Footer img based on Tyh comment

Removed aria-label from Footer img based on Tyh comment

---

component-library/src/app/pages/QA/michael/michael.component.ts

- Related story [890777](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/890777)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-indicator_fix/en/michael-en)
- When user has selected number indicator but changes it to text, the indicator should automatically update to the default text indicator and vice versa.
- Flip indicator type and check if label is updated

Small bugs fixes for the indicators.

---

component-library/src/app/pages/banner-documentation/banner-doc-code.component.ts
component-library/src/assets/locales/en.json
component-library/src/assets/locales/fr.json

* Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/921150))
* Fixed issue where Link was not being removed from banner, also fixed a translation typo
* Observables ere suffixed with 'Obs$' (ex: …

Banner bug

---

component-library/component-lib/src/lib/form-components/checkbox/checkbox.component.html

* Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/919910))
* Small fix to pass accessibility scan for unique ID's on the declaration checkbox - 1 line fix.
* Observables ere …

make checkbox label id unique from label component

---

component-library/src/app/components/accordion-panel/accordion-container.component.html
component-library/src/app/components/accordion-panel/accordion-container.component.scss
component-library/src/app/components/accordion-panel/accordion-container.component.ts
component-library/src/app/components/code-viewer/code-viewer.component.scss
component-library/src/app/components/resizable-container/resizable-container.component.scss

- Related story [908182](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/908182)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-code_view_button/en/input-documentation)
- Move hide code button to left when on mobile
- Matched paddings to figma design
- Shrink browser to mobile width
- Compare code view with [Figma design](https://www.figma.com/file/TPwx1HcbXRCZeIDePI4Y4N/Documentation-Site?type=design&node-id=371-9948&mode=dev)

Fix Hide code, and Copy code on code view

---

component-library/component-lib/src/lib/header-footer/header/header.component.html
component-library/src/app/shell/shell.component.html
component-library/src/app/shell/shell.component.scss

Related story [908182](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_boards/board/t/JL%20-%20Design%20System/Backlog%20items/?workitem=914125)
[QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-shell-landmarks/en/overview)
##What is this pull request doing?
Fixing the landmark accessibility issues with the app
Run the page through an automated tool.

Refactoring shell

---

component-library/component-lib/src/lib/header-footer/language-switch/language-switch.component.ts

* Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/909658))
* Small fix to the tablet breakpoint which toggles the abbreviated text in FR and EN to display when the viewport is less than 768px

updated tablet breakpoint for abbreviated lang text

---

buildspec.yml

hot fix to buildspec to align with install script changes

---

core-library/component-styling/navigation/navigation-item.scss
core-library/component-styling/navigation/navigation.scss

- Updated the width to be 100% of its parent container's width.
- Removed unnecessary padding around lib-navigation
- Tried to adjust the icon locations

Removed padding and updated width

---

component-library/src/app/shell/shell.component.ts
core-library/component-styling/navigation/navigation-item.scss

Aligning the iconTrailing

---

component-library/component-lib/src/lib/shared/navigation/nav-item-accordion/nav-item-accordion.component.html
component-library/component-lib/src/lib/shared/navigation/nav-item-nav/nav-item-nav.component.html
component-library/src/app/pages/QA/accessibility-demo/accessibility-demo-next-page/accessibility-demo-next-page.component.html
component-library/src/app/pages/QA/accessibility-demo/accessibility-demo-next-page/accessibility-demo-next-page.component.ts
component-library/src/app/pages/QA/accessibility-demo/accessibility-demo-previous-page/accessibility-demo-previous-page.component.html
component-library/src/app/pages/QA/accessibility-demo/accessibility-demo-previous-page/accessibility-demo-previous-page.component.ts
core-library/component-styling/hidden-nav/_hidden-nav.scss

Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_boards/board/t/JL%20-%20Design%20System/Backlog%20items/?workitem=903497))
Fixes missing hidden nav for accessibility demo. 
Removes tabindex from components other than hidden nav.

fixing demo page bugs

---

core-library/component-styling/tabs/_tabs.scss

[QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-demo_button/en/buttons)

Tab last button: remove 4px right

---

core-library/component-styling/breadcrumb/_breadcrumb.scss

[QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-breadcrumb_abbr/en/michael-en)

Breadcrumb abbr: remove dotted underline

---

component-library/src/app/pages/banner-documentation/banner-doc-code.component.ts

* Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/924651))
* Fixes the issue where the title, description, and size was not updating correctly in the code-viewer
* Observables ere suffixed with …

fix banner code block

---

component-library/src/app/components/resizable-container/resizable-container.component.scss

* Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/926014))
* Padding changes in the resizable container broke the resize function by adding 20px of height for every 1px mouse movement. Changed to margin to restore the behaviour while matching the design spec.
* Subjects are suffixed with 'Subj' (ex: …

bugfix resize-container

---

component-library/src/app/components/component-preview/component-preview.component.scss
component-library/src/app/pages/input-documentation/input-doc-code.component.scss
component-library/src/app/pages/input-documentation/input-documentation.component.scss
component-library/src/app/pages/input-documentation/input-documentation.component.ts
core-library/component-styling/input-component/_input-component.scss

* Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/930029))
* Updated component preview styles for Input component
* The next section of ticket(margin and padding of whole page) is not fixed here(will have another ticket)

Updated component preview style for Input doc page

---

core-library/component-styling/breadcrumb/_breadcrumb.scss

* Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/932202))
* Updated padding around **home** on Breadcrumb component

Updated Breadcrumb home item

---

component-library/src/assets/locales/en.json
component-library/src/assets/locales/fr.json

Add missing path for autocomplete

Add missing path for autocomplete

---

component-library/src/app/pages/button-documentation/button-documentation.component.scss
component-library/src/app/pages/for-developers/for-developers.component.scss
component-library/src/app/shell/shell.component.scss
component-library/src/scss/_page.scss
core-library/component-styling/navigation/navigation.scss

- Related task [937616](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/937616)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-content-margin-fix/en/overview)
- Correct margin for content container
- Add 4px margin to navigation scrollbar
1. Go to [qa page](https://d1whfh0luwluq8.cloudfront.net/qa-content-margin-fix/en/overview)
2. Verify above issues are addressed

Margin is not matching with figma

---

component-library/component-lib/src/lib/form-components/textarea/textarea.component.ts

* Related story #([Task1](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/934934)) #([Task2](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/934941))
* set character length to 0 when value is an empty string or when null to fix the above mentioned bugs

Fixed accessibility bugs on text area

---

component-library/component-lib/src/lib/shared/icon-button/icon-button.component.ts
component-library/src/app/pages/icon-button-documentation/icon-button-doc-code.component.ts
core-library/component-styling/icon-button/_icon-button.scss

* Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/937901))
* Updates icon-btn font awesome class to match design
* Updates icon size for xsmall, small, and large per design review

update icon sizes and class to match spec

---

core-library/component-styling/flyout/_flyout.scss

fix for flyout margins

---

component-library/component-lib/src/lib/shared/navigation/navigation.component.html
component-library/component-lib/src/lib/shared/navigation/navigation.component.ts
component-library/src/app/pages/overview/overview.component.scss
component-library/src/scss/_grid.scss
component-library/src/scss/styles.scss

- Related task [939575](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/939575)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-overview-fix/en/overview)
- Overview page: align columns
- Enable support for gutter in our columns
- Fix left side nav shifting issue
1. Go to [qa page](https://d1whfh0luwluq8.cloudfront.net/qa-overview-fix/en/overview)
2. Verify columns are aligned
3. Scroll down page, verify left nav is not shifting

Overview Page is not matching with figma

---

component-library/component-lib/src/lib/shared/navigation/navigation.component.ts
core-library/component-styling/navigation/navigation.scss

[QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-overview-fix/en/overview)

Left nav follow up fix

---

component-library/src/app/pages/select-documentation/select-doc-code.component.ts
component-library/src/app/pages/select-documentation/select-documentation.component.html

- Related story [938332](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/938332?src=WorkItemMention&src-action=artifact_link)
- Updated the language toggle for Select doc page
- Refactored mobile view

Updated language toogle for Select doc page + mobile view

---

component-library/component-lib/src/lib/form-components/checkbox/checkbox.component.html
component-library/component-lib/src/lib/form-components/checkbox/checkbox.component.ts

- Fixing issues with control value accessors within the checkbox component.

Control value accessor changes for checkbox

---

core-library/component-styling/banner/_banner.scss

Fixed banner text overflow issue.

Fixed text overflow issue on banner

---

component-library/src/app/pages/QA/mahsa/mahsa.component.ts
component-library/src/app/pages/autocomplete-documentation/autocomplete-documentation.component.ts
component-library/src/app/pages/button-documentation/button-doc-code.component.ts
component-library/src/app/pages/button-documentation/button-documentation.component.html
component-library/src/app/pages/date-picker-documentation/date-picker-doc-code.component.ts
component-library/src/app/pages/date-picker-documentation/date-picker-documentation.component.html
component-library/src/app/pages/date-picker-documentation/date-picker-documentation.component.ts
component-library/src/app/pages/icon-button-documentation/icon-button-doc-code.component.ts
component-library/src/app/pages/icon-button-documentation/icon-button-documentation.component.ts
component-library/src/app/pages/input-documentation/input-doc-code.component.ts
component-library/src/app/pages/input-documentation/input-documentation.component.html
component-library/src/app/pages/input-documentation/input-documentation.component.ts
component-library/src/app/pages/select-documentation/select-documentation.component.html
component-library/src/app/pages/spinner-documentation/spinner-doc-code.component.ts
component-library/src/app/pages/spinner-documentation/spinner-documentation.component.html
component-library/src/app/pages/utilities/utilities.component.html
component-library/src/assets/locales/en.json
component-library/src/assets/locales/fr.json

**Why were these changes introduced?**
To clean up the translations file and to minimize the size of our JSON files as much as possible.
**What does this PR accomplish?**
- Removes unnecessary strings.
- Updates removed strings to use General string keys.

Updating duplicate text to General strings

---

component-library/src/app/components/component-preview/component-preview.component.scss

Why were these changes introduced?
To resolve the strange width bug for the banner doc site.

fix for Banner preview

---

component-library/src/app/app.component.ts
component-library/src/app/components/side-nav/side-nav.component.ts

- Related bug [936307](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/936307)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-page-index-fix/en/datePicker-doc)
- Fix tab cannot reach content area
1. Go to [qa page](https://d1whfh0luwluq8.cloudfront.net/qa-page-index-fix/en/datePicker-doc)
2. Verify tab can reach content area and order is correct

Right Side Nav Focus Issue

---

component-library/component-lib/src/lib/form-components/input/input.component.html
component-library/component-lib/src/lib/form-components/input/input.component.ts

- Related bug [945099](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/945099)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-password-fix/en/input-documentation)
- Fix password type when toggled from basic to password
- Fix password toggle button disabled by default

Input Interactive demo - "Password" field turned "disable" behavior by default.

---

component-library/src/app/pages/overview/overview.component.scss

What does this PR do?
Fixes minor 2px padding from a link.

Fix for overview link padding

---

component-library/src/app/shell/shell.component.ts
component-library/src/assets/locales/en.json
component-library/src/assets/locales/fr.json

Added Translations for left side nav

Added French translation keys for side nav

---

component-library/src/app/pages/input-documentation/input-doc-code.component.ts
component-library/src/app/pages/select-documentation/select-doc-code.component.html
component-library/src/app/pages/select-documentation/select-doc-code.component.ts

- Added disable banner for select doc page
-  Fixed default behavior for required toggle on Input doc page to match figma

Minor enhancements

---

component-library/src/app/pages/icon-button-documentation/icon-button-documentation.component.scss
component-library/src/app/pages/input-documentation/input-documentation.component.scss

[QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-component-preview-fix/en/input-documentation)

Component preview mobile fix

---

core-library/component-styling/input-component/_input-component.scss

Disabled default eye icon in ms edge

Ms edge password icon bug fix

---

component-library/component-lib/src/lib/form-components/checkbox/checkbox.component.html
component-library/component-lib/src/lib/form-components/checkbox/checkbox.component.ts
component-library/component-lib/src/lib/form-components/multi-checkbox/multi-checkbox.component.css
component-library/component-lib/src/lib/form-components/multi-checkbox/multi-checkbox.component.html
component-library/component-lib/src/lib/form-components/multi-checkbox/multi-checkbox.component.ts
component-library/component-lib/src/lib/form-components/radio-input/radio-input.component.html
component-library/component-lib/src/lib/shared/label/label.component.html
component-library/component-lib/src/lib/shared/label/label.component.ts
component-library/src/app/pages/checkbox-documentation/checkbox-doc-code.component.ts

Related story [943788](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/943788)
[QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-checkbox-interactive-demo-labels/en/checkbox-documentation)
This PR should fix the issue of having multiple checkboxes for the Interactive demo component page.
TESTING
Navigate to Checkbox page and run the Waves accessibility tool on the page.

Fixing orphaned labels and multicheckbox labels

---

component-library/src/app/components/side-nav/side-nav.component.ts

- Fixed scroll issue on right side nav
- Fixed first element not being selected onLoad issue on right side nav

Bug fixes on right side navv

---

component-library/src/app/components/side-nav/side-nav.component.ts

Fixed the focus issue on date picker

Removed on blur which was breaking the focus for elements

---

component-library/component-lib/src/lib/form-components/date-picker/date-picker.component.html
component-library/component-lib/src/lib/form-components/date-picker/date-picker.component.ts
component-library/src/app/components/side-nav/side-nav.component.ts
core-library/component-styling/progress-indicator/_progress-indicator.scss

- Updated Datepicker error issue + Progress Indicator style

Bug/datepicker - progress indicator

---

component-library/src/app/components/side-nav/side-nav.component.scss
component-library/src/app/components/side-nav/side-nav.component.ts
component-library/src/app/shell/shell.component.ts
core-library/tokens/button/_button-const.scss

* Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/949428))
* Resolves the space between the left side nav and the content in tablet/mobile
* Right side nav height reduced to avoid collapsing over the footer on scroll in tablet mode
* typo correction to the button consts

Bug - Navigation height

---

component-library/component-lib/src/lib/form-components/checkbox/checkbox.component.ts
component-library/src/app/pages/QA/michael/michael.component.ts

Updated config property helpText in checkbox to hint so that the name is consistent with other components

Updated helptText to hint

---

core-library/typography/_fa-wrapper.scss

Related story #([948564](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_boards/board/t/JL%20-%20Design%20System/Backlog%20items/?workitem=948564))
- Updated fa-wrapper file based on its usage on the Checkbox component!

Updated fa-wrapper file

---

component-library/component-lib/src/lib/banner-component/banner/banner.component.html
component-library/src/app/pages/banner-documentation/banner-doc-code.component.ts

* Related story #(https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/943778)
* Refactored banner doc component
* updated toggle config to match figma
* Fixed radio button not getting disabled after 3 buttons have already been added to the banner
* Fixed Button sizes in banner not being updated with size of banner
* …

Banner bug fixes

---

component-library/component-lib/src/lib/shared/tabs/tabs.component.html

Fixed active tab not getting translated issue

Fixed active tab translation bug

---

core-library/component-styling/banner/_banner.scss

Updated link styles for banner to match figma

Fixed link styles on banner

---

component-library/component-lib/src/lib/header-footer/language-switch/language-header-footer-switch.service.ts
core-library/component-styling/label/_label-component.scss

- updated word-break to break word instead of break-all
- Added a check for system and dark mode in language toggle to fix hardcoding scheme which breaks the header img

Fix header and label bugs

---

component-library/component-lib/src/lib/form-components/date-picker/date-picker.component.ts

Change YYYY select to descending order

change year to descending

---

component-library/src/app/app-routing.module.ts
component-library/src/app/components/side-nav/side-nav.component.ts
component-library/src/app/components/title-slug-url/title-slug-url.component.html

[QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-side-nav-active/en/datePicker-doc)

Right-side nav bugs

---

core-library/component-styling/navigation/navigation-item.scss

[QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-left-nav-outline/en/overview)

Left nav: fix focus outline cut off
