component-library/component-lib/src/lib/checkbox/checkbox.component.html

A recent merge did not properly resolve conflict in `component-library/component-lib/src/lib/checkbox/checkbox.component.html`, brought back changes from https://github.com/IRCC-ca/ds-sdc-dev/pull/59/files#diff-d1c38f8d5e9a6e5547376f73875594d1e165d5749bd822073d572cb049114df3

Checkbox: bring back label after merge conflict

---

component-library/src/app/gallery/QA/michael/michael.component.ts
core-library/component-styling/indicator/_indicator.scss

- ensure text label is centre at all time
- Large number indicator size should be 28 x 28px
Small number indicator size should be 24 x 24px
- When user has selected number indicator but changes it to text, the indicator should automatically update to the default text indicator and vice versa
- Number indicator should not have icon variable
- Large size use body 3 text for all

Indicator: misc bug fixes

---

core-library/component-styling/breadcrumb/_breadcrumb.scss

Should be 4px padding on separators
Should be 12px from the breadcrumb item (currently there is 8px margin and 8px padding totalling 16px instead of 12)

Breadcrumb: Space between separators and items

---

core-library/tokens/global/_categories.scss

grey weak - Hsl value corrected to 240 11 96 as per Figma.
red-weak, green weak, purple weak, navy-weak are already same as HSL value.

Indicator: correct color

---

component-library/src/app/pages/input-documentation/input-documentation.component.html
component-library/src/app/pages/input-documentation/input-documentation.component.scss

Input documentation style fix

---

component-library/component-lib/src/lib/shared/breadcrumb/breadcrumb.component.ts
component-library/component-lib/src/lib/shared/breadcrumb/link/link.component.html

* Fixing bug [907614](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/907614) & [907616](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/907616)
* Breadcrumb: only tab once to move to next item
* Breadcrumb: fix wave tool warning of elipsis button aria text

Breadcrumb accessibility fixes

---

component-library/src/app/components/title-slug-url/title-slug-url.component.html
component-library/src/app/components/title-slug-url/title-slug-url.component.scss
component-library/src/app/components/title-slug-url/title-slug-url.component.ts

* Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/874903)
* Updated copy url to use plain button instead of using <a> tags
* updated styles for title slug url
':void' is removed from void functions
* Ensure the code contain appropriate media queries and accessibility elements
* Is the acceptance criteria met?
**Review component stylesheets:**
* New sheet …

Bug-Fix: Changed copy ulr to use Plain button instead of <a>

---

component-library/src/app/components/accordion-panel/accordion-container.component.html
component-library/src/app/components/accordion-panel/accordion-container.component.scss
component-library/src/app/components/accordion-panel/accordion-container.component.ts
component-library/src/app/components/code-viewer/code-viewer.component.ts
component-library/src/app/components/interactive-demo/interactive-demo.component.scss
component-library/src/app/components/interactive-demo/interactive-demo.component.ts
component-library/src/app/pages/button-documentation/button-doc-code.component.scss

* Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/876832))
* Added the following mobile styles for interactive demo
* Accordion should hide when switch to mobile view.
* Toggle config should switch to single column view
*  Accordion toggle Heading should center and always take 100% in mobile if only item
* Fixed other minor styles  
':void' is removed …

Bug-Fix: fixed mobile styles for interactive demo

---

component-library/src/app/components/title-slug-url/title-slug-url.component.ts
component-library/src/app/pages/banner-documentation/banner-doc-code.component.ts
component-library/src/app/pages/input-documentation/input-documentation.component.html
component-library/src/app/pages/input-documentation/input-documentation.component.scss
component-library/src/app/pages/input-documentation/input-documentation.component.ts
component-library/src/app/share/documentation-page-headings.ts
component-library/src/app/share/lan-switch/interface/content-item.interface.ts
component-library/src/app/shell/shell.component.html

* Following team discussion on code optimization versus static template - refactored input documentation to remove all instances of ngFor and some small issues flagged
* Moved title slug configs to general file and clean up the component ts file
* Small fix to the figma section and how images were behaving responsively
* Clean up stylesheet
':void' is removed from …

input-documentation page cleanup

---

component-library/src/app/pages/input-documentation/input-doc-code.component.ts

Fix [907582](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/907582)
Removes the Error state from the demo component when you user toggles the radio buttons.
- form_interactive_input to formInteractiveInput
- Adding markAsUntouched() when there is no error
- Refactoring parseCodeViewConfig() method.

Fixing Error state on input demo

---

core-library/component-styling/breadcrumb/_breadcrumb.scss

- Related story [907943](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_boards/board/t/JL%20-%20Design%20System/Backlog%20items/?workitem=907943)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-breadcrumb_overflow/en/michael-en)
- Correct color on overflow links
- Correct hover state on overflow links
- Compare breadcrumb overflow with [Figma design](https://www.figma.com/file/TSKk5lWdgAvZdE836kWcbK/Patterns?type=design&node-id=4129-67016&t=8H0TTHcDAhzSXpjT-4)

Bug: Breadcrumb overflow menu is not as per the design

---

component-library/component-lib/src/lib/shared/icon/icon.component.html
core-library/component-styling/icon-button/_icon-button.scss
core-library/component-styling/spinner/_spinner.scss

Related story [914167](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/914167/)
[QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-button-id-of-ds-icon-container-must-be-unique/en/overview)
Replacing the #ds-icon-container selector with .ds-icon-container
Pass the pages through a WCAG tool to make sure we no longer have the ds-icon-container duplicate ID error.

Bug: ds-icon-container-must-be-unique

---

core-library/component-styling/select/_select-component.scss
core-library/tokens/checkbox/_checkbox.scss
core-library/tokens/input/_input-const.scss
core-library/tokens/radio/_radio.scss

- Removed invalid from component tokens
**Explanation:**
Having `invalid` and `.ng-invalid.ng-touched` at the same time will remain the select in error state all the time, no matter what you do

Removed invalid from component tokens

---

core-library/component-styling/breadcrumb/_breadcrumb.scss

- Related story [903578](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/903578)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-breadcrumb_center/en/michael-en)
- Center overflow menu relative to ellipsis
- Compare breadcrumb overflow with [Figma design](https://www.figma.com/file/TPwx1HcbXRCZeIDePI4Y4N/Documentation-Site?type=design&node-id=13-2210&t=GmyU0vBSBszEfaZG-0)

Breadcrumb: centre overflow menu to elipsis

---

component-library/component-lib/src/lib/shared/indicator/indicator.component.ts

- Related story [907976](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/907976)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-indicate_pst_event/en/michael-en)
- Fix length detection when pasting a long string for indicator
1. Go to https://d1whfh0luwluq8.cloudfront.net/qa-indicate_pst_event/en/michael-en page and click on "Indicator Component".
2. Select the type as "Text", and Add the Label as "Immigration Refugee Citizenship of Canada"
3. You should notice the Indicator is showing truncated size.

Indicator: Text size should not be wider than 200px at any given time.

---

component-library/component-lib/src/lib/shared/button/button.component.html
component-library/component-lib/src/lib/shared/button/button.component.ts
component-library/component-lib/src/lib/shared/icon/icon.component.ts
core-library/component-styling/icon/_icon.scss

- Related story [922323](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/922323)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-button_icon_size/en/buttons)
- Replace `ButtonSize` enum with `DSSizes`
- Correct button icon size to 20x20 (small) & 24x24 (large)
- Scroll to button demo
- Change Icon to Leading or Trailing
- Check icon size

Button: standardize icon size

---

component-library/src/app/components/code-viewer/code-viewer.component.scss
component-library/src/app/shell/shell.component.scss
core-library/component-styling/icon-button/_icon-button.scss

- Related story [924002](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/924002)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-page_container/en/input-documentation)
- Page container: fix cut off issue
- Button icon: set icon `X` height back to 24px as blurry issue does not exist on QA's Mac
1. Go to [input page](https://d1whfh0luwluq8.cloudfront.net/qa-page_container/en/input-documentation) or any other component page
2. Shrink screen to check if content area is cutting off

Issue with Content Container on Input Documentation Page

---

component-library/src/app/pages/banner-documentation/banner-doc-code.component.html
component-library/src/app/pages/code-view/code-view.component.ts
component-library/src/app/pages/icon-button-documentation/icon-button-doc-code.component.html
component-library/src/app/pages/overview/overview.component.html
component-library/src/app/shell/shell.component.scss

* Related story -URL(https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/924009)
* removed extra divs and inline styles in banner and icon-btn interactive demo/code block pages to align them with all the other documentation pages
* Fixes the code-view selector from 'app-overview' (which already exists) to app-code-view
* Changes content-area responsive to flex-start to align according to design
* Remove auto margin from footer to align with container
** File names and hierarchies are in keeping …

Bug 924009 Doc Site overall content margin issue

---

core-library/component-styling/breadcrumb/_breadcrumb.scss

* Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/924146))
* Updated padding to the breadcrump to align content centered on keyboard focus

fix breadcrumb alignment on keyboard focus

---

component-library/component-lib/src/lib/form-components/input/input.component.html
core-library/component-styling/error/_error.scss
core-library/component-styling/label/_label-component.scss

Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/924863))
QA Link #([URL](https://d1whfh0luwluq8.cloudfront.net/qa-tech-debt--design-changes/en/input-documentation))
Making a few CSS changes to match the new design, and fixing a bug where the size would not be reflected in the input error component

Added CSS changes and small bugfix to input

---

component-library/src/app/pages/banner-documentation/banner-documentation.component.html
component-library/src/app/pages/banner-documentation/banner-documentation.component.scss
component-library/src/app/pages/input-documentation/input-documentation.component.html
component-library/src/app/pages/overview/overview.component.html
component-library/src/app/pages/overview/overview.component.scss
component-library/src/app/shell/shell.component.html
component-library/src/app/shell/shell.component.scss

Related stories #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/903473/?workitem=926923)) & #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_boards/board/t/JL%20-%20Design%20System/Backlog%20items/?workitem=923942))
- Removed extra space below images on Banner & Input doc pages
- Updated Anatomy margin to 24px.
- On Overview page updated headers to `<h2>` with h3 style
- Updated IRCC Design System to `<p>` with h2 style

Updated styles

---

component-library/src/app/components/side-nav/side-nav.config.ts
component-library/src/app/pages/QA/accessibility-demo/accessibility-demo-next-page/accessibility-demo-next-page.component.ts
component-library/src/app/pages/request-form/request-form.component.html
component-library/src/app/pages/request-form/request-form.component.scss
component-library/src/app/pages/request-form/request-form.component.ts
component-library/src/app/shell/shell.component.ts

* Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/924652))
* Removes CTA from config which was adding extra margin to the banner container
* Adds new 'Support' section in the left side nav with the request form as a child item
* Adds right side nav to page
* *Does Not** refactor the content container margins - this is captured in a different story 
* Interfaces start with 'I' followed by a capital letter and camel case …

bug: request form banner height and side navs

---

component-library/component-lib/src/lib/form-components/radio-input/radio-input.component.ts

- Related story [920324](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/920324)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-radio-error/en/mike-en)
- Fix radio error message does not show up in aria label
1. Go to [qa page](https://d1whfh0luwluq8.cloudfront.net/qa-radio-error/en/mike-en) then click radio component
2. Toggle radio button with 1- 2 errors
3. Verify error message show up in aria label

Radio error aria label fix

---

component-library/src/app/pages/banner-documentation/banner-documentation.component.html

* Related task #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/929249))
* Removes h5 class from h3 tags which was applying the wrong font weight
* Observables ere suffixed with 'Obs$' (ex: thisIsAnExampleObs$)
* …

Banner Documentation Font Weight Fix

---

component-library/component-lib/src/shared/constants/jl-components.constants.ts
component-library/src/app/components/component-preview/component-preview.component.html
component-library/src/app/components/component-preview/component-preview.component.scss
component-library/src/app/components/component-preview/component-preview.component.ts
component-library/src/app/pages/button-documentation/button-documentation.component.html
component-library/src/app/pages/button-documentation/button-documentation.component.ts

- Related story [929702](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/929702)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-button-doc-fix/en/buttons)
- Change component preview mobile cut point
- Change button page mobile img cut point to 767px
1. Go to [qa page](https://d1whfh0luwluq8.cloudfront.net/qa-button-doc-fix/en/buttons)
2. Compare with [design](https://www.figma.com/file/TPwx1HcbXRCZeIDePI4Y4N/Documentation-Site?type=design&node-id=590-20111&mode=design&t=pPi1WQoawK9s1G1h-4)

Qa/button doc fix: Images are not correctly sized for various devices (Desktop, Mobile, Tablet).

---

component-library/component-lib/src/lib/shared/indicator/indicator.component.ts

- Related task [923994](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/923994)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-indicator-no-tab/en/michael-en)
- Disable tab for indicator component
1. Go to [qa page](https://d1whfh0luwluq8.cloudfront.net/qa-indicator-no-tab/en/michael-en)
2. Verify indicator cannot be tabbed into

Indicator: Should not be able to tab in to the Indicator component

---

component-library/src/app/components/side-nav/side-nav.component.scss

hot fix for the right side nav height collapsing on the footer.

reduce vh to 90 for side nav to avoid collapse over the footer

---

component-library/component-lib/src/lib/form-components/input/input.component.ts

- Related bug [938590](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/938590)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-input-demo-bug/en/input-documentation)
- Fix issue input field in the Basic tab keeps the password input value.
1. Go to [qa page](https://d1whfh0luwluq8.cloudfront.net/qa-input-demo-bug/en/input-documentation)
2. Choose password type
3. Put random value at input field, then click eye icon to hide it.
4. Flip back to Basic, verify input show up as normal text.

Input field in the Basic tab keeps the password input value.

---

component-library/component-lib/src/lib/shared/breadcrumb/breadcrumb.component.html
component-library/component-lib/src/lib/shared/breadcrumb/breadcrumb.component.ts
component-library/component-lib/src/lib/shared/breadcrumb/link/link.component.html
component-library/src/assets/locales/en.json
component-library/src/assets/locales/fr.json
core-library/component-styling/breadcrumb/_breadcrumb.scss

- Related bug [933015](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/933015)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-breadcrumb-nav/en/michael-en)
- Wrap breadcrumb in nav tag
- Add aria label to breadcrumb
1. Go to [qa page](https://d1whfh0luwluq8.cloudfront.net/qa-breadcrumb-nav/en/michael-en) and click Breadcrumb
2. Verify breadcrumb styling has no change

Breadcrumb must be imbedded in a <nav> tag

---

component-library/component-lib/src/lib/form-components/radio-input/radio-input.component.html
component-library/component-lib/src/lib/form-components/radio-input/radio-input.component.ts
component-library/src/app/components/interactive-demo/interactive-demo.component.ts
component-library/src/app/pages/autocomplete-documentation/autocomplete-documentation.component.ts
component-library/src/app/pages/button-documentation/button-doc-code.component.ts
component-library/src/app/pages/date-picker-documentation/date-picker-doc-code.component.ts
component-library/src/app/pages/icon-button-documentation/icon-button-doc-code.component.ts
component-library/src/app/pages/input-documentation/input-doc-code.component.ts
component-library/src/app/pages/request-form/request-form.component.ts

* Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/932997))
* Fixing issues with control value accessors within the radio component.
* Updates radio template
* Lint
* Observables ere suffixed with …

update radio component control values disabled state handling

---

component-library/src/app/pages/input-documentation/input-doc-code.component.ts

- Related story [934584](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/934584)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-input-doc-enhance/en/input-documentation)
- The password field Label read 'Password' when type password is chosen
1. Go to [qa page](https://d1whfh0luwluq8.cloudfront.net/qa-input-doc-enhance/en/input-documentation)
2. Click password, verify label & typescript config has changed.

Input Documentation Enhancement

---

component-library/src/app/components/component-preview/component-preview.component.scss

- Related story [934385](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/934385)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-component-preview/en/buttons)
Desktop & tablet:
- Container is fluid based on component
- Left and right padding of 64px
- Top padding of 60px
- Bottom padding of 44px
- Margin of 12px between component and "copy style" button
Mobile:
- Width fills mobile container
- Component is center-aligned
- Top padding of 60px
- Bottom padding of 44px
1. Go to [qa page](https://d1whfh0luwluq8.cloudfront.net/qa-component-preview/en/buttons)
2. Verify component preview is same as [design …

Component preview enhancement

---

component-library/src/app/pages/input-documentation/input-doc-code.component.html
component-library/src/app/pages/input-documentation/input-doc-code.component.ts

- Related story [934584](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/934584)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-input-doc-enhance/en/input-documentation)
- Add required to label text for both basic and password input
- Hide placeholder config when on password tab
1. Go to [qa page](https://d1whfh0luwluq8.cloudfront.net/qa-input-doc-enhance/en/input-documentation)
2. Click required, verify **(required)** is added to label
3. Click password, verify **(required)** stays on label
4. Verify placeholder config is hidden

Input Documentation Enhancement #2

---

component-library/component-lib/src/lib/form-components/autocomplete/autocomplete.component.ts
component-library/component-lib/src/lib/form-components/input/input.component.ts
component-library/component-lib/src/lib/shared/flyout/flyout.component.ts
component-library/src/app/pages/autocomplete-documentation/autocomplete-documentation.component.ts
core-library/component-styling/input-component/_input-component.scss

- Related story [938496](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/938496)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-autocomplete-fix/en/autocomplete-documentation)
- Match initial config for interactive demo with [Figma](https://www.figma.com/file/TPwx1HcbXRCZeIDePI4Y4N/Documentation-Site?type=design&node-id=4596-148445&mode=design&t=79BXgMmTyiyPaPcw-0)
- Highlight 1st option when autocomplete get focus
- Keep flyout visible when user clear input
1. Go to [qa page](https://d1whfh0luwluq8.cloudfront.net/qa-autocomplete-fix/en/autocomplete-documentation)
2. Check if initial config match figma
3. Click input field, check if 1st option is …

Autocomplete: Various mismatch with figma and some functionality refactoring.

---

component-library/src/app/pages/autocomplete-documentation/autocomplete-documentation.component.ts

- Related story [938496](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/938496)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-autocomplete-fix/en/autocomplete-documentation)
- Match initial config for interactive demo with [Figma](https://www.figma.com/file/TPwx1HcbXRCZeIDePI4Y4N/Documentation-Site?type=design&node-id=4596-148445&mode=design&t=79BXgMmTyiyPaPcw-0), fix description toggle
1. Go to [qa page](https://d1whfh0luwluq8.cloudfront.net/qa-autocomplete-fix/en/autocomplete-documentation)
2. Check if initial config match figma

Autocomplete demo: fix description initial state #2

---

component-library/src/app/pages/input-documentation/input-doc-code.component.html
component-library/src/app/pages/input-documentation/input-doc-code.component.ts

- Related story [934584](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/934584)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-input-doc-code-fix/en/input-documentation)
- Fix when user selects Multiple error option, a input "test" is populated in the input field for both password and basic inputs
- Fix When the single option is selected, entering text into the input field removes the error however, when selecting multiple error option, text in the input field does not remove the 3 error lines
- Consolidate 3 configs into one for error state management
1. Go to [qa page](https://d1whfh0luwluq8.cloudfront.net/qa-input-doc-code-fix/en/input-documentation) …

Input Documentation Enhancement #3

---

component-library/component-lib/src/lib/shared/indicator/indicator.component.html

* Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/914321))
* Adds a role to the indicator component container to fix accessibility issue 'Elements must only use the allowed aria attributes'
TEST
* Build and run the project locally
* Navigate to Michael's QA page
* Open the indicator component
* Access dev tools - Axe Dev Tools - scan the page
* The 'Elements must only use the allowed aria attributes' should no longer be found in the scan
* Aria role for reference: #([URL](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/group_role))

Add role to indicator component

---

component-library/src/assets/locales/en.json

Small translation fix to update the date picker title to 'Date Picker' rather than Date picker per spec.

fix date picker title

---

component-library/component-lib/src/lib/form-components/autocomplete/autocomplete.component.html
component-library/component-lib/src/lib/form-components/error/error.component.html
component-library/component-lib/src/lib/form-components/error/error.component.ts
component-library/component-lib/src/lib/form-components/input/input.component.html
component-library/component-lib/src/shared/functions/stand-alone.functions.ts
component-library/src/app/pages/autocomplete-documentation/autocomplete-documentation.component.ts
core-library/component-styling/error/_error.scss

- Related bug [943716](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/d006c866-0d87-4b32-93cb-f457d4ec2c0b/_workitems/edit/943716)
- [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-autocomplete-fix/en/autocomplete-documentation)
- Refactor autocomplete demo to use standalone set error instead of swap out form controls
- Fix error icon disappears when toggling placeholder
- Refactor lib-error icon to use ircc-cl-lib-icon component
1. Go to [qa page](https://d1whfh0luwluq8.cloudfront.net/qa-autocomplete-fix/en/autocomplete-documentation)
2. Verify no error message on initial state
3. Toggle error to **True**
4. Input anything in text input, toggle placeholder to **True**
5. Verify error icon does not disappear

Bug: Error icon disappears when toggling placeholder

---

component-library/src/app/pages/input-documentation/input-doc-code.component.ts

- Reduce code duplication by moving setForms to setFormError & call it in input-doc-code

Input demo: refactor to use standalone setFormErrors function

---

component-library/component-lib/src/lib/header-footer/language-switch/language-switch.component.html

Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/936332))
* Adds a tabindex="0" to language toggle component so it is reachable via sequential keyboard navigation

Language Toggle Focus

---

component-library/component-lib/src/lib/banner-component/banner/banner.component.ts
component-library/component-lib/src/lib/form-components/checkbox/checkbox.component.html
component-library/component-lib/src/lib/form-components/checkbox/checkbox.component.ts
component-library/component-lib/src/lib/form-components/date-picker/date-picker.component.ts
component-library/component-lib/src/lib/form-components/select/select.component.html
component-library/component-lib/src/lib/form-components/select/select.component.ts

Related story #([955368](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_boards/board/t/JL%20-%20Design%20System/Backlog%20items/?workitem=955368))
- Reviewed and cleaned all config properties!

Update and cleanup for configs

---

component-library/component-lib/src/lib/shared/icon-button/icon-button.component.html
component-library/component-lib/src/lib/shared/navigation/navigation.component.html

* Related story [950504](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/950504)
* [QA Link](https://d1whfh0luwluq8.cloudfront.net/qa-icon-button-empty/en/overview)
* Fixes the bug discovered using the "Empty Heading" bug in Waves in relation to the icon-button component.

Icon Button has too many empty button fix

---

component-library/src/app/components/title-slug-url/title-slug-url.component.html

Fixed copy url not reading on screen reader

Fixed Copy url not reading on screen reader

---

component-library/component-lib/src/lib/form-components/textarea/textarea.component.html
component-library/component-lib/src/lib/form-components/textarea/textarea.component.ts
core-library/component-styling/textarea/_textarea.scss

* Related story #([URL](https://alm-tfs.apps.ci.gc.ca/tfs/IRCC/Scrum/_workitems/edit/951962))
* Discussion between the story developer and the reviewer to clarify and confirm where needed
* Added keypress listener to listen to all keypresses once max limit has reached and announce max limit reached for each keypress after
* Added translation for respected variables
* Interfaces start with 'I' followed by a capital letter and camel case (IInterfaceExample) and are …

Textarea announce Max char limit reached on each keypress
